document: feedback-pipeline-workload
version: 1
data:
  name: FreeIPA Server - minimal
  description: FreeIPA server
  maintainer: sst_identity_management

  packages:
  - freeipa-server

  labels:
  - eln

  package_placeholders:
    pki-servlet-engine:
      description: This package provides a Tomcat-like servlet engine in RHEL 8+
      requires:
       - ant
       - java-headless
       - java-devel
       - jpackage-utils
       - procps
       - shadow-utils
       - chkconfig
       - systemd-units
       - coreutils
      buildrequires:
       - ant
       - findutils
       - java-devel
       - jpackage-utils
       - maven-local
       - systemd-unnits
